cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'
urlpatterns = [
    path('',views.cars,name='cars'),
    
]

cars_world/urls.py
import django
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cars/',include('cars.urls')),
    path('contacts/',include('contacts.urls')),
    path('oauth2/', include('social_django.urls', namespace='social')),
    path("404/", views.custom_page_not_found),


]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'
urlpatterns = [
   path('inquiry/',views.inquiry,name='inquiry'),
    
]

pages/urls.py
from django.urls import path
from . import views
from cars.views import car_detail,search

app_name = 'pages'

urlpatterns = [
    
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('services/',views.services,name='services'),
    path('contact/',views.contact,name='contact'),
    path('privacy/',views.privacy_policy,name='privacy'),
    #this is for searching and car_details
    path('<int:id>/',car_detail,name='car_detail'),
    path('search/',search,name='search'),
    #this is for login and register forms#
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
]

contacts/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    car_id = models.IntegerField()
    customer_need = models.CharField(max_length=100)
    car_title = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    message =  models.TextField(blank=True)
    user_id =  models.IntegerField(blank=True)
    created_date = models.DateTimeField(blank=True,default=datetime.now)

    def __str__(self):
        return self.email
        

contacts/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import Contact
from django.core.mail import send_mail
from django.contrib.auth.models import User

# Create your views here.
def inquiry(request):
    if request.method=='POST':
        firstname = request.POST['first_name']
        lastname = request.POST['last_name']
        car_id = request.POST['car_id']
        customer_need = request.POST['customer_need']
        car_title = request.POST['car_title']
        city = request.POST['city']
        state = request.POST['state']
        email = request.POST['email']
        phone = request.POST['phone']
        message =  request.POST['message']
        user_id =  request.POST['user_id']
        if user_id == "0":
            messages.error(request,"you must be logged in inorder to inquire about a specific car !")
            return redirect("pages:login")
        else:
            if request.user.is_authenticated:
                user_id = request.user.id
                has_contacted = Contact.objects.all().filter(car_id=car_id,user_id=user_id)
                if has_contacted:
                    messages.error(request,"you already filed inquiry about this car.please be patient until we get back to you!")
                    return redirect("/"+car_id) 
            contact = Contact(first_name=firstname,last_name=lastname,car_id=car_id,customer_need=customer_need,
            car_title=car_title,city=city,state=state,email=email,phone=phone,message=message,user_id=user_id)
            #here sending emails part#
            admin_emails = []
            admin_info = User.objects.filter(is_superuser = True)
            for item in admin_info:
                admin_emails.append(item.email)
            send_mail(
                'New Car inquiry about car '+car_title+' check here.',
                'Heyy! admin. You got a new car inquiry about car '+car_title+'.please login to admin panel for more info. this inquiry is setup by '+firstname+' '+lastname+' send him/her feedback as soon as possible.',
                'developervenkatesh2001@gmail.com',
                admin_emails,
                fail_silently=False,
            )
            
            contact.save()
            messages.success(request,"your request has been submitted, we will get back to you shortly.")
            return redirect("/"+car_id)

templates/pages/about.html
{%extends 'base.html'%}

{% block title %}| who we are{% endblock %}
{% block content %}
{% load static %}
<!--sub-banner starting-->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>About Us</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">About Us</li>
            </ul>
        </div>
    </div>
</div>
<!--sub-banner ending here-->

<!-- Service center start -->
<div class="about-car content-area-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-6">
                <div class="about-car-photo">
                    <div id="carDetailsSlider" class="carousel car-details-sliders slide">
                        <!-- main slider carousel items -->
                        <div class="carousel-inner">
                            <div class="active item carousel-item" data-slide-number="0">
                                <img src= "{% static 'img/car/car-1.jpg' %}" class="img-fluid" alt="slider-car">
                            </div>
                            <div class="item carousel-item" data-slide-number="1">
                                <img src="{% static 'img/car/car-2.jpg' %}" class="img-fluid" alt="slider-car">
                            </div>
                            <div class="item carousel-item" data-slide-number="2">
                                <img src="{% static 'img/car/car-3.jpg' %}" class="img-fluid" alt="slider-car">
                            </div>
                        </div>
                        <!-- main slider carousel nav controls -->
                        <ul class="carousel-indicators car-properties list-inline nav nav-justified">
                            <li class="list-inline-item active">
                                <a id="carousel-selector-0" class="selected" data-slide-to="0" data-target="#carDetailsSlider">
                                    <img src="{% static 'img/car/car-1.jpg' %}" class="img-fluid" alt="small-car">
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a id="carousel-selector-1" data-slide-to="1" data-target="#carDetailsSlider">
                                    <img src="{% static 'img/car/car-2.jpg' %}" class="img-fluid" alt="small-car">
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a id="carousel-selector-2" data-slide-to="2" data-target="#carDetailsSlider">
                                    <img src="{% static 'img/car/car-3.jpg' %}" class="img-fluid" alt="small-car">
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
            
            <div class="col-xl-7 col-lg-6 align-self-center">
                <div class="best-used-car">
                    <h3>Welcome to <span>Car Zone</span></h3>
                    <p><b>The Abstract of this website - </b>CAR ZONE is a website which acts as a platform for the user to choose his/her favourite car. they can register and login to the site or they can directly login with the Social media accounts like Facebook, Google and Linkedin without registering. they can navigate all through the site and explore their favourite car in the list of cars provided.To provide smooth experience, all the details of the specific car is provided in each individual page of the specific car. The user can show their interest on the car by clicking on the send message button in that respective page of that car. if he/she wants to post their car for selling, they can navigate to contact page and contact the admin by filling the form. this form is directly send to admin mail. after that admin directly gets in touch with the respective person. this feature is designed just to stop the fake postings of the car sellers. The admin checks the car and it's details before posting the car into website.</p>
                    <br>
                    <br>
                </div>
            </div>
            <br>
            <div class="col-xl-5 col-lg-7">
                <div class="about-car-photo">
                    <div id="carDetailsSlider" class="carousel car-details-sliders slide">
                        <!-- main slider carousel items -->
                        <div class="carousel-inner">
                            <div class="active item carousel-item" data-slide-number="0">
                            <a href="https://www.linkedin.com/in/venkateshnagumantri" target="_blank">
                                <img src= "{% static 'img/me/my_webphoto2.jpg' %}" style="border-radius:3px 50% !important;"  class="img-fluid" alt="slider-car">
                            </a>
                            </div>
                        </div>
                        <!-- main slider carousel nav controls -->
                    </div>
                </div>
            </div>
            <div class="col-xl-7 col-lg-6 align-self-center">
                <div class="best-used-car">
                    <p class="mb-0"><b>About the developer -</b> "Hi! This is <b>Venkatesh Nagumantri</b> and I am currently studying 2nd year in Master of Computer Applications at Gayatri Vidya Parishad College of Engineering, Visakhapatnam. This Website is My personal Project. I developed this website with self-interest so that i can test my Full Stack web development skills and know my extent of knowledge in them. This project took 6 months in total from the starting stage of imagining page layouts to final stage of deployment. I learnt a lot in this whole journey. if you are impressed by the design and features of this website you can reach me on mail or Linkedin. My mail id is <a href="#" style="color:red;"><b>venkateshnagumantri11@gmail.com</b></a> and Linkedin id is <a href="https://www.linkedin.com/in/venkateshnagumantri" target="_blank" style="color:blue;"><b>Venkatesh Nagumantri</b></a>. Thank you.".</p>
                </div>
            </div>





        </div>
    </div>
</div>
<!-- Service center end -->



<!-- Our team start -->
<div class="our-team content-area">
    <div class="container">
        <!-- Main title -->
        <div class="main-title">
            <h1>Executive <span>Team</span></h1>
            <h5>Here have a look at the sample team and their imaginary designations</h5>
        </div>
        <!-- Slick slider area start -->
        <div class="slick-slider-area clearfix">
            <div class="row slick-carousel" data-slick='{"slidesToShow": 4, "responsive":[{"breakpoint": 1024,"settings":{"slidesToShow": 2}}, {"breakpoint": 768,"settings":{"slidesToShow": 1}}]}'>
                {%for person in Team %}
                <div class="slick-slide-item">
                    <div class="team-1">
                        <div class="photo">
                            <a href="#">
                                <img src="{{person.photo.url}}" alt="team-1" class="img-fluid">
                            </a>
                            <div class="social-list clearfix">
                                <a href="{{person.linkedin_link}}" target="_blank" class="facebook-bg"><i class="fa fa-linkedin"></i></a>
                                <a href="{{person.twitter_link}}" target="_blank" class="twitter-bg"><i class="fa fa-twitter"></i></a>
                                <a href="{{person.google_plus__link}}" target="_blank" class="google-bg"><i class="fa fa-google"></i></a>
                            </div>
                        </div>
                        <div class="details">
                            <h4><a href="team-detail.html">{{person.first_name}} {{person.last_name}}</a></h4>
                            <h5>{{person.designation}}</h5>
                        </div>
                    </div>
                </div>                
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Our team end -->
{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}

{% block title %}| Contact Us{% endblock  %}
{% block content %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Contact Us</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home'%}">Home</a></li>
                <li class="active">Contact Us</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- Contact 2 start -->
<div class="contact-2 content-area-5">
    <div class="container">
        <!-- Main title -->
        <div class="main-title text-center">
            <h1>Contact <span>Us</span></h1>
            <p>Got any Doubt or Want to sell your car? Contact us by filling the form. We will get in touch with you.</p>
        </div>
        <form action="{% url 'pages:contact' %}" method="POST" enctype="multipart/form-data">
            {% include 'includes/messages.html' %}
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-7">
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <div class="form-group name">
                                <input type="text" name="first_name" class="form-control" placeholder="First Name" {%if user.is_authenticated%} value={{user.first_name}} {%endif%} AutoFocus required>
                            </div>
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="form-group name">
                                <input type="text" name="last_name" class="form-control" placeholder="Last Name" {% if user.is_authenticated%} value={{user.last_name}} {% endif %} required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group email">
                                <input type="email" name="email" class="form-control" placeholder="Email" required>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group subject">
                                <input type="text" name="subject" class="form-control" placeholder="Subject" required>
                            </div>
                        </div>

                        
                        <div class="col-md">
                            <div class="form-group number">
                                <input type="text" name="phone" class="form-control" placeholder="Phone Number" required>
                            <div id='emailHelp' class='form-text'>&nbsp We'll never share your phone number with anyone else outside </div>
                            </div>
                        </div>
                        
                        
                        <div class="col-md-12">
                            <div class="form-group message">
                                <textarea class="form-control" name="message" placeholder="Write message"></textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="send-btn text-center">
                                <button type="submit" class="btn btn-md button-theme">Send Message</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="contact-info-2">
                        <div class="ci-box">
                            <div class="icon">
                                <i class="flaticon-phone"></i>
                            </div>
                            <div class="detail">
                                <h5>Phone:</h5>
                                <p><a href="#">+91-63XX-922-5X5</a></p>
                            </div>
                        </div>
                        <div class="ci-box">
                            <div class="icon">
                                <i class="flaticon-mail"></i>
                            </div>
                            <div class="detail">
                                <h5>Email:</h5>
                                <p><a href="#">venkateshnagumantri11@gmail.com</a></p>
                            </div>
                        </div>
                        <div class="ci-box">
                            <div class="icon">
                                <i class="flaticon-earth"></i>
                            </div>
                            <div class="detail">
                                <h5>Web:</h5>
                                <p><a href="{% url 'pages:about' %}">info@carzone.com</a></p>
                            </div>
                        </div>
                        <div class="ci-box mb-0">
                            <div class="icon">
                                <i class="flaticon-fax"></i>
                            </div>
                            <div class="detail">
                                <h5>Fax:</h5>
                                <p><a href="#">+0477 85X6 552</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Contact 2 end -->




{% endblock %}

templates/pages/dashboard.html
{% extends 'base.html' %}

{% block title %}| Dashboard{% endblock title %}
{% block content %}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Dashboard</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">{{user.first_name}}</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!--   Dashboard Start   -->

<div class="container mt-50 mb-50">
	{% include 'includes/messages.html' %}
	<div class="main-title" style="text-align:left !important;">
            <h1>Welcome <span>{{user.first_name}}</span></h1>
            <p>Here are the cars that you have inquired about</p>
        </div>
		{%if inquiries %}
			<table class="table table-hover">
				<thead>
			  	<tr>
					<th scope="col">#</th>
					<th scope="col">Car Name</th>
					<th scope="col">Location</th>
					<th scope="col">Inquiry Reason</th>
					<th scope="col">Action</th>
			  	</tr>
				</thead>
				<tbody>
			  {% for inquiry in inquiries %}
			  	<tr>
					<th scope="row">{{ forloop.counter }}</th>
					<td>{{inquiry.car_title}}</td>
					<td>{{inquiry.city}}</td>
					<td>{{inquiry.customer_need}}</td>
					<td><a href="{% url 'pages:car_detail' inquiry.car_id %}" class="btn btn-outline-dark">View Car</a></td>
			  	</tr>
			  
				{%endfor%}
				</tbody>
		  	</table>
		{%else%}
			<h4> Until now, you have not inquired about any car. go ahead and find your favourite one. </h4>
		{%endif%}
</div>

<!--   Dashboard End   -->

{% endblock %}

templates/pages/login.html
{% extends 'base.html' %}

{% block title %}| Login{% endblock %}
{% block content %}

{% load static %}
<!--Sub banner start-->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Login Here</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">Login</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- Contact section start -->
<div class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="form-section">
                    <div class="logo-2">
                        <a href="{% url 'pages:home' %}">
                            <img src="{% static 'img/logos/black-logo.png' %}" alt="logo">
                        </a>
                    </div>
                    <br>
                    <h3>Sign into your account</h3>
                    {%include 'includes/messages.html'%}
                    <form action="{% url 'pages:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group form-box">
                            <input type="text" name="field" class="input-text" placeholder="Enter username or email adress" style="color:black !important;" AutoFocus required>
                            <i class="flaticon-mail"></i>
                        </div>
                        <div class="form-group form-box">
                            <input type="password" name="password" class="input-text" placeholder="Password" style="color:black !important;" required>
                            <i class="flaticon-lock"></i>
                        </div>
                        <div class="form-group mb-0 clearfix">
                            <button type="submit" class="btn-md btn-theme float-left">Login</button>
                        </div>
                        <div class="extra-login clearfix">
                            <span>Or Login With</span>
                        </div>
                        <div class="clearfix"></div>
                        <ul class="social-list" style="word-spacing:20px; !important" >
                            <li><a href="{% url 'social:begin' 'facebook'  %}" class="facebook-bg"><i class="fa fa-facebook facebook-i"></i><span>Facebook</span></a></li>
                            <li><a href="{% url 'social:begin' 'google-oauth2' %}" class="google-bg"><i class="fa fa-google google-i"></i><span>Google</span></a></li>
                            <li><a href="{% url 'social:begin' 'linkedin-oauth2' %}" class="linkedin-bg"><i class="fa fa-linkedin linkedin-i"></i><span>Linkedin</span></a></li>
                        </ul>
                    </form>
                    <p>Don't have an account? <a href="{% url 'pages:register' %}" style="color:rgb(0,0,237) !important;" class="thembo"><b> Register here</b></a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact section end -->
{% endblock  %}

templates/pages/register.html
{%extends 'base.html'%}


{% block title %}| Register{% endblock %}
{%block content%}

{% load static %}

<!--Sub banner start-->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Register Here</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">Register</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<!-- Contact section start -->
<div class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="form-section">
                    <div class="logo-2">
                        <a href="{% url 'pages:home' %}">
                            <img src="{% static 'img/logos/black-logo.png' %}" alt="logo">
                        </a>
                    </div>
                    <br>
                    <h3>Create an account</h3>
                    {%include 'includes/messages.html'%}
                    <form action="{% url 'pages:register' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group form-box">
                            <input type="text" name="firstname" class="input-text" placeholder="First Name" style="color:black !important;" AutoFocus required>
                            <i class="fa fa-user"></i>
                        </div>
                        <div class="form-group form-box">
                            <input type="text" name="lastname" class="input-text" placeholder="Last Name" style="color:black !important;" required>
                            <i class="fa fa-user"></i>
                        </div>
                        <div class="form-group form-box">
                            <input type="text" name="username" class="input-text" placeholder="Username" style="color:black !important;" required>
                            <i class="fa fa-user"></i>
                        </div>
                        <div class="form-group form-box">
                            <input type="email" name="email" class="input-text" placeholder="Email Address" style="color:black !important;" required>
                            <i class="flaticon-mail"></i>
                        </div>
                        <div class="form-group form-box">
                            <input type="password" name="password" class="input-text" placeholder="Password" style="color:black !important;" required>
                            <i class="flaticon-lock"></i>
                        </div>
                        <div class="form-group form-box" required>
                            <input type="password" name="confirm_password" class="input-text" placeholder="Confirm Password" style="color:black !important;" required>
                            <i class="flaticon-lock"></i>
                        </div>
                        <div class="form-group form-box">
                        <p style="font-size:80%;">
                            By clicking REGISTER, you agree to the Car Zone <a href="{% url 'pages:privacy' %}" target="_blank" style="color:blue;">Privacy Policy</a> and <a href="{% url 'pages:privacy' %}" target="_blank" style="color:blue;">Cookie Policy</a>.
                        </p>
                        </div>
                        <div class="form-group mb-0 clearfix"  >
                            <button type="submit" class="btn-md btn-theme float-left">Register</button>
                        </div>
                        <div class="extra-login clearfix">
                            <span>Or Login With</span>
                        </div>
                        <div class="clearfix"></div>
                        <ul class="social-list" style="word-spacing:20px; !important">
                            <li><a href="{% url 'social:begin' 'facebook' %}" class="facebook-bg"><i class="fa fa-facebook facebook-i"></i><span>Facebook</span></a></li>
                            <li><a href="{% url "social:begin" "google-oauth2" %}" class="google-bg"><i class="fa fa-google google-i"></i><span>Google</span></a></li>
                            <li><a href="{% url 'social:begin' 'linkedin-oauth2' %}" class="linkedin-bg"><i class="fa fa-linkedin linkedin-i"></i><span>Linkedin</span></a></li>
                        </ul>
                    </form>
                    <p>Already a member? <a href="{% url 'pages:login' %}" style="color:rgb(0,0,237) !important;" class="thembo"><b>Login here</b></a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact section end -->
{% endblock %}