cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'
urlpatterns = [
    path('',views.cars,name='cars'),
    
]

cars_world/urls.py
import django
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cars/',include('cars.urls')),
    path('contacts/',include('contacts.urls')),
    path('oauth2/', include('social_django.urls', namespace='social')),
    path("404/", views.custom_page_not_found),


]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from cars.views import car_detail,search

app_name = 'pages'

urlpatterns = [
    
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('services/',views.services,name='services'),
    path('contact/',views.contact,name='contact'),
    path('privacy/',views.privacy_policy,name='privacy'),
    #this is for searching and car_details
    path('<int:id>/',car_detail,name='car_detail'),
    path('search/',search,name='search'),
    #this is for login and register forms#
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
]

templates/includes/footer.html
<footer class="footer">
    
    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <p class="copy" >© {%now 'M Y'%} CarZone Corp. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4">
                    <div class="social-list-2">
                        <ul>
                            <li><a href="https://www.facebook.com" target = "__blank" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://twitter.com" target = "__blank" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.google.com" target = "__blank" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="https://www.linkedin.com/company/89722630/" target = "__blank" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/messages.html
{% if messages %}

  {% for message in messages %}
      <div id="message" class="container">
        <div class="alert alert-{{ message.tags }}" alert-dismissable role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>

            <strong>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                  Error:
              {% else %}
                  {{mesaage.tags|title}}
              {% endif %}
            </strong>
            {{message}}
        </div>
      </div>
  {% endfor %}

{% endif %}

templates/includes/navbar.html
{% load static %}
<header class="main-header sticky-header header-with-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand company-logo"  href="{%url 'pages:home'%}">
                <img src=" {% static '/img/logos/black-logo.png' %} " alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a
                        {% if '/' == request.path %}
                         class="nav-link dropdown-toggle active "   
                        {% else %}
                         class="nav-link dropdown-toggle "   
                        {% endif %}
                        href="{% url 'pages:home' %}" >
                        Home 
                    </a>

                    </li>
                    <li class="nav-item">
                        <a
                        {% if '/cars/' == request.path %}
                            class="nav-link active"
                        {% else %}
                            class="nav-link"
                        {% endif %} 
                        href="{% url 'cars:cars' %}">
                            Cars
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                        {% if '/about/' == request.path %}
                         class="nav-link active " 
                        {% else %}
                         class="nav-link" 
                        {%endif%}
                        href="{% url 'pages:about' %}">
                            About
                        </a>

                    </li>
                    <li class="nav-item">
                        <a
                        {% if '/services/' == request.path %}
                        class="nav-link active" 
                        {%else%}
                        class="nav-link" 
                        {%endif%}
                        href="{% url 'pages:services' %}">
                            Services
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a
                        {% if '/contact/' == request.path %}
                        class="nav-link active" 
                        {%else%}
                        class="nav-link" 
                       {% endif %}
                        href="{% url 'pages:contact' %}">
                            Contact
                        </a>

                    </li>


                    <li class="nav-item dropdown m-hide">
                        <a href="#full-page-search" class="nav-link h-icon">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

templates/includes/topbar.html
<header class="top-header th-2 top-header-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-7">
                <div class="list-inline">
                    <a href="tel:+91-63XX-922-5X5"><i class="fa fa-phone"></i>+91-63XX-922-5X5</a>
                    <a href="tel:venkateshnagumantri11@gmail.com"><i class="fa fa-envelope"></i>venkateshnagumantri11@gmail.com</a>
                    <a href="tel:#"><i class="fa fa-clock-o"></i>Mon - Sun: 8:00am - 6:00pm</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-5">
                <ul class="top-social-media pull-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'pages:dashboard' %}" class="sign-in"><i class="fa fa-tachometer"></i>Dashboard</a>
                    </li>
                    <li>
                        <a href="javascript:{document.getElementById('logout').submit()}" class="sign-in"><i class="fa fa-sign-out"></i> Logout</a>
                        <form action = "{% url 'pages:logout' %}" id="logout" method="POST">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                    </li>

                    {% else %}
                    <li>
                        <a href="{% url 'pages:login' %}" class="sign-in"><i class="fa fa-sign-in"></i> Login</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:register' %}" class="sign-in"><i class="fa fa-user"></i> Register</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </div>
</header>