cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'
urlpatterns = [
    path('',views.cars,name='cars'),
    
]

cars_world/urls.py
import django
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('cars/',include('cars.urls')),
    path('contacts/',include('contacts.urls')),
    path('oauth2/', include('social_django.urls', namespace='social')),
    path("404/", views.custom_page_not_found),


]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from cars.views import car_detail,search

app_name = 'pages'

urlpatterns = [
    
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('services/',views.services,name='services'),
    path('contact/',views.contact,name='contact'),
    path('privacy/',views.privacy_policy,name='privacy'),
    #this is for searching and car_details
    path('<int:id>/',car_detail,name='car_detail'),
    path('search/',search,name='search'),
    #this is for login and register forms#
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
]

cars/models.py
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField
from multiselectfield import MultiSelectField
from django.core.validators import MinValueValidator,MaxValueValidator
from cloudinary.models import CloudinaryField
# Create your models here.
class Car(models.Model):
    state_choices=(
        ('AP','Andhra Pradesh'),
        ('AR','Arunachal Pradesh'),
        ('AS','Assam'),
        ('BR','Bihar'),
        ('CH','Chhattisgarh'),
        ('GOA','Goa'),
        ('GJ','Gujarat'),
        ('HAR','Haryana'),
        ('HP','Himachal Pradesh'),
        ('JK','Jammu and Kashmir'),
        ('JD','Jharkhand'),
        ('KAR','Karnataka'),
        ('KER','Kerala'),
        ('MP','Madhya Pradesh'),
        ('MH','Maharashtra'),
        ('MNP','Manipur'),
        ('MEG','Meghalaya'),
        ('MZ','Mizoram'),
        ('NGL','Nagaland'),
        ('ODI','Odisha'),
        ('PUN','Punjab'),
        ('RJ','Rajasthan'),
        ('SK','Sikkim'),
        ('TN','Tamil Nadu'),
        ('TG','Telangana'),
        ('TR','Tripura'),
        ('UP','Uttar Pradesh'),
        ('UT','Uttarakhand'),
        ('WB','West Bengal')

    )
    door_choices = (
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
    )

    features_choices = (
        ('Cruise Control', 'Cruise Control'),
        ('Audio Interface', 'Audio Interface'),
        ('Airbags', 'Airbags'),
        ('Air Conditioning', 'Air Conditioning'),
        ('Seat Heating', 'Seat Heating'),
        ('Alarm System', 'Alarm System'),
        ('ParkAssist', 'ParkAssist'),
        ('Power Steering', 'Power Steering'),
        ('Reversing Camera', 'Reversing Camera'),
        ('Direct Fuel Injection', 'Direct Fuel Injection'),
        ('Auto Start/Stop', 'Auto Start/Stop'),
        ('Wind Deflector', 'Wind Deflector'),
        ('Bluetooth Handset', 'Bluetooth Handset'),
    )

    year_choices = []
    for r in range(2000, (datetime.now().year+1)):
        year_choices.append((r,r))

        
    car_title=models.CharField(max_length=100)
    state=models.CharField(choices=state_choices,max_length=100)
    city=models.CharField(max_length=100)
    color=models.CharField(max_length=100)
    model=models.CharField(max_length=100)
    year=models.IntegerField(('year'),choices=year_choices)
    condition=models.CharField(max_length=100)
    price=models.IntegerField(validators=[MinValueValidator(100000)])
    description=RichTextField()
    car_photo= CloudinaryField('image')
    car_photo_1= CloudinaryField('image')
    car_photo_2= CloudinaryField('image')
    car_photo_3= CloudinaryField('image')
    car_photo_4= CloudinaryField('image')
    features = MultiSelectField(choices = features_choices)
    body_style=models.CharField(max_length=100)
    engine=models.CharField(max_length=100)
    transmission=models.CharField(max_length=100)
    interior_color=models.CharField(max_length=100)
    miles=models.IntegerField()
    doors=models.CharField(choices=door_choices,max_length=100)
    passengers=models.IntegerField()
    vin_no=models.CharField(max_length=100)
    milege = models.IntegerField()
    fuel_type=models.CharField(max_length=100)
    no_of_owners=models.IntegerField()
    is_featured=models.BooleanField(default=False)
    created_date=models.DateTimeField(default=datetime.now,blank=True)


    def __str__(self):
        return self.car_title
    
    

cars/views.py
from django.shortcuts import render,get_object_or_404
from .models import Car
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
# Create your views here.

def cars(request):
    all_cars = Car.objects.all().order_by('-created_date')

    model_search = Car.objects.values_list('model',flat=True).distinct()
    city_search = Car.objects.values_list('city',flat=True).distinct()
    year_search = Car.objects.values_list('year',flat=True).distinct().order_by('year')
    body_style_search = Car.objects.values_list('body_style',flat=True).distinct()

    for item in all_cars :
        prc=str(item.price)
        lastprc = prc[-3:]
        firstprc=prc[ :-3]
        firstprc=firstprc[::-1]
        s=""
        for i in range(len(firstprc)):
            if i!=0 and i%2==0:
                s=s+','+firstprc[i]
            else:
                s=s+firstprc[i]
        s=s[::-1]
        prc=s+','+lastprc
        item.price = prc

    page=request.GET.get('page')
    paged_cars = Paginator(all_cars,4).get_page(page)
    cars_list={
        'cars': paged_cars,
        'model_search':model_search,
        'city_search' : city_search,
        'year_search' : year_search,
        'body_style_search':body_style_search
    }
    return render(request,'cars/cars.html',context= cars_list)

def car_detail(request,id):
    single_car = get_object_or_404(Car,pk=id)
    prc = str(single_car.price)
    lastprc = prc[-3:]
    firstprc=prc[ :-3]
    firstprc=firstprc[::-1]
    s=""
    for i in range(len(firstprc)):
        if i!=0 and i%2==0:
            s=s+','+firstprc[i]
        else:
            s=s+firstprc[i]
    s=s[::-1]
    prc=s+','+lastprc
    single_car.price = prc

    data = {
        'car_data' : single_car
    }
    return render(request,'cars/car_detail.html', context=data)

def search(request):
    cars_list= Car.objects.all().order_by('-created_date')

    car_title_search = Car.objects.values_list('car_title',flat=True).distinct()
    model_search = Car.objects.values_list('model',flat=True).distinct()
    city_search = Car.objects.values_list('city',flat=True).distinct()
    year_search = Car.objects.values_list('year',flat=True).distinct().order_by('year')
    body_style_search = Car.objects.values_list('body_style',flat=True).distinct()
    engine_search = Car.objects.values_list('engine',flat=True).distinct()
    
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            cars_list = cars_list.filter(description__icontains=keyword)
    
    if 'car_title' in request.GET:
        car_title = request.GET['car_title']
        if car_title:
            cars_list = cars_list.filter(car_title__iexact=car_title)
    
    if 'model' in request.GET:
        model = request.GET['model']
        if model:
            cars_list = cars_list.filter(model__iexact=model)
    
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            cars_list = cars_list.filter(city__iexact=city)

    if 'year' in request.GET:
        year = request.GET['year']
        if year:
            cars_list = cars_list.filter(year__iexact=year)
    
    if 'body_style' in request.GET:
        body_style = request.GET['body_style']
        if body_style:
            cars_list = cars_list.filter(body_style__iexact=body_style)

    if 'engine' in request.GET:
        engine = request.GET['engine']
        if engine:
            cars_list = cars_list.filter(engine__iexact=engine)

    if 'min_price' in request.GET:        
        min_price = request.GET['min_price']
        max_price = request.GET['max_price']
        if max_price:
            cars_list = cars_list.filter(price__gte=min_price,price__lte=max_price)

    car_title_search = Car.objects.values_list('car_title',flat=True).distinct()
    model_search = Car.objects.values_list('model',flat=True).distinct()
    city_search = Car.objects.values_list('city',flat=True).distinct()
    year_search = Car.objects.values_list('year',flat=True).distinct().order_by('year')
    body_style_search = Car.objects.values_list('body_style',flat=True).distinct()
    engine_search = Car.objects.values_list('engine',flat=True).distinct()
    #for humanizing indian currency prices of cars
    for item in cars_list :
        prc=str(item.price)
        lastprc = prc[-3:]
        firstprc=prc[ :-3]
        firstprc=firstprc[::-1]
        s=""
        for i in range(len(firstprc)):
            if i!=0 and i%2==0:
                s=s+','+firstprc[i]
            else:
                s=s+firstprc[i]
        s=s[::-1]
        prc=s+','+lastprc
        item.price = prc
    
    data = {
        'searched_cars':cars_list,
        'car_title_search':car_title_search,
        'model_search':model_search,
        'city_search' : city_search,
        'year_search' : year_search,
        'body_style_search':body_style_search,
        'engine_search' : engine_search,
    }

    return render(request,'cars/search.html',context=data)

templates/cars/cars.html
{% extends 'base.html' %}

{% block title %}| Our Car Inventory{% endblock %}
{% block content %}
{%load humanize%}

<!-- Sub banner start -->
<div class="sub-banner overview-bgi">
    <div class="container breadcrumb-area">
        <div class="breadcrumb-areas">
            <h1>Our Car Inventory</h1>
            <ul class="breadcrumbs">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li class="active">Cars</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->


<!-- Featured car start -->
<div class="featured-car content-area">
    <div class="container">
        <div class="row">
            
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {%for car in cars%}
                    <div class="col-lg-6 col-md-6">
                        <div class="car-box-3">
                            <div class="car-thumbnail">
                                <a href="{% url 'pages:car_detail' car.id %}" class="car-img">
                                    <div class="tag">For Sale</div>
                                    <div class="price-box">
                                        <span>₹ {{car.price}}</span>
                                    </div>
                                    <img class="d-block w-100" src="{{car.car_photo.url}}" alt="car" style="min-height:260px; max-height:260px;">
                                </a>
                                <div class="carbox-overlap-wrapper">
                                    <div class="overlap-box">
                                        <div class="overlap-btns-area">
                                            <div class="car-magnify-gallery">
                                                <a href="{{car.car_photo.url}}" class="overlap-btn">
                                                    <i class="fa fa-expand"></i>
                                                    <img class="hidden" src="{{car.car_photo.url}}">
                                                </a>
                                                {%if car.car_photo_1%}
                                                <a href="{{car.car_photo_1.url}}" class="hidden" >
                                                    <img class="hidden" src="{{car.car_photo_1.url}}">
                                                </a>
                                                {%endif%}
                                                {%if car.car_photo_2%}
                                                <a href="{{car.car_photo_2.url}}" class="hidden">
                                                    <img class="hidden" src="{{car.car_photo_2.url}}">
                                                </a>
                                                {%endif%}
                                                {%if car.car_photo_3%}
                                                <a href="{{car.car_photo_3.url}}" class="hidden">
                                                    <img class="hidden" src="{{car.car_photo_3.url}}">
                                                </a>
                                                {%endif%}
                                                {%if car.car_photo_4%}
                                                <a href="{{car.car_photo_4.url}}" class="hidden" >
                                                    <img class="hidden" src="{{car.car_photo_4.url}}">
                                                </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="detail">
                                <h1 class="title">
                                    <a href="{% url 'pages:car_detail' car.id %}">{{car.car_title}}</a>
                                </h1>
                                <div class="location">
                                    <a href="{% url 'pages:car_detail' car.id %}">
                                        <i class="flaticon-pin"></i>{{car.state}}, {{car.city}}
                                    </a>
                                </div>
                                <ul class="facilities-list clearfix">
                                    <li>{{car.fuel_type}}</li>
                                    <li>{{car.miles| intcomma}} km</li>
                                    <li>{{car.transmission}}</li>
                                    <li>{{car.body_style}}</li>
                                    <li>{{car.color}}</li>
                                    <li>{{car.year}}</li>
                                </ul>
                            </div>
                        
                        </div>
                    </div>
                {%endfor%}
                </div>
                <!-- Page navigation start -->
                <div class="pagination-box p-box-2 text-center">
                    <nav aria-label="Page navigation example">
                        {% if cars.has_other_pages %}
                        <ul class="pagination">
                            {%if cars.has_previous%}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{cars.previous_page_number}}"><i class="fa fa-angle-left"></i></a>
                                </li>
                            {%else%}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#"><i class="fa fa-angle-left"></i></a>
                                </li>
                            {%endif%}

                            {% for i in cars.paginator.page_range %}
                                {%if cars.number == i%}
                                <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                {%endif%}
                            {% endfor %}
                            {%if cars.has_next%}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{cars.next_page_number}}"><i class="fa fa-angle-right"></i></a>
                                </li>
                            {%else%}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
                                </li>
                            {%endif%}
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="sidebar-right">
                    <!-- Advanced search start -->
                    <div class="widget advanced-search2">
                        <h3 class="sidebar-title">Search your desire car</h3>
                        <form action="{% url 'pages:search' %}" method="">
                            <div class="form-group">
                                <input type="text" name="keyword" placeholder="Search by name of the car" class="form-control">
                            </div>
                            
                            <div class="form-group">
                                <select class="form-control search-fields" name="model">
                                    <option selected="true" disabled="disabled">Model</option>
                                    {% for model in model_search %}
                                    <option value="{{model}}" >{{model}} </option>
                                    {%endfor%}
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <select class="form-control search-fields" name="city">
                                    <option selected="true" disabled="disabled">City</option>
                                    {% for city in city_search %}
                                    <option value="{{city}}">{{city}}</option>
                                    {%endfor%}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="year">
                                    <option selected="true" disabled="disabled">Year</option>
                                    {% for year in year_search %}
                                    <option value="{{year}}" >{{year}}</option>
                                    {%endfor%}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control search-fields" name="body_style">
                                    <option selected="true" disabled="disabled">Select Type Of Car</option>
                                    {% for body_style in body_style_search %}
                                    <option value="{{body_style}}"  >{{body_style}}</option>
                                    {%endfor%}
                                </select>
                            </div>
                            <div class="range-slider clearfix">
                                            <label>Price</label>
                                            <div data-min="0" data-max="50000000"  data-min-name="min_price" data-max-name="max_price" data-unit="INR" class="range-slider-ui ui-slider" aria-disabled="false"></div>
                                            <div class="clearfix"></div>
                                        </div>
                            <div class="form-group">
                                <button class="btn btn-block button-theme btn-md">
                                    <i class="fa fa-search"></i> Search
                                </button>
                            </div>
                        </form>
                    </div>
                   
                    <!-- Question start -->
                    <div class="widget question widget-3">
                        <h5 class="sidebar-title">Follow us</h5>
                        <div class="social-list clearfix">
                            <ul>
                                <li><a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#" class="rss-bg"><i class="fa fa-rss"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/89722630/" target="_blank"class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featured car end -->

{% endblock %}